FROM ubuntu as ClaatExporter

# get the claat binaries
RUN apt-get update \
 && apt-get install -y wget \
 && wget https://github.com/googlecodelabs/tools/releases/download/v2.2.6/claat-linux-amd64 -O /claat \
 && chmod u+x /claat 

ENTRYPOINT [ "/claat" ]

CMD [ "-h" ]
